### ISSUE TITLE
Is it possible to set example value for fields

### ISSUE THREAD

**Issue by bmihelac** [axnsan12/drf-yasg#129]
Hello,

I am looking to set *example* attribute of model property but cannot find example in documentation or source code.

Basically, I would like swagger.yaml  to create attribute [here](https://github.com/axnsan12/drf-yasg/blob/aca0c4713e0163fb0deea8ea397368084a7c83e5/tests/reference.yaml#L1485-L1489), like this:

```yaml
    properties:
      title:
        description: title model help_text
        type: string
        maxLength: 255
        minLength: 1
        example: My title
```

Then result documentation would include "My title" instead of "string" like in screenshot:

![example-title](https://user-images.githubusercontent.com/13813/40327968-07a3d890-5d45-11e8-93e0-4e9b43d6337e.png)

Is that possible? Would appreciate direction where to look.
