### ISSUE TITLE
SerializerMethodField can no longer be hinted with Optional types

### ISSUE THREAD

**Issue by chaosk** [axnsan12/drf-yasg#385]
Hello!

It seems that a recent change in 753be1a made it so SerializerMethodField methods can no longer be annotated with `typing.Optional`.

Used versions:
* python 3.7.2
* django 2.2.2
* djangorestframework 3.9.4
* drf-yasg 1.16.0

Example code:
```python
class PetSerializer(serializers.ModelSerializer):
    human_age = serializers.SerializerMethodField()

    def get_human_age(self, obj) -> Optional[int]:
        if obj.human_age_multiplier is None:
            return None
        return math.floor(obj.age * obj.human_age_multiplier)

    class Meta:
        model = Pet
```

Expected result:
```yaml
human_age:
  title: Human age
  type: integer
  readOnly: true
  x-nullable: true
```

Actual result:
```yaml
human_age:
  title: Human age
  type: string
  readOnly: true
```
