### ISSUE TITLE
`help_text` on a SerializerMethodField not displayed if list type

### ISSUE THREAD

**Issue by khameeteman** [axnsan12/drf-yasg#838]
# Bug Report

## Description

Help text is not displayed in the following case:

```python
class Serializer(serializers.ModelSerializer):
    field = serializers.SerializerMethodField('_field', help_text="field info")

    def _field(self) -> list[dict]:
        return []
```

generates `openapi.yml`:

```yml
field:
  description: field info
  type: array
  items:
    type: object
```

The `description` key is missing in the `items` dict.

## Is this a regression?

Don't know

## Minimal Reproduction

```code

```

## Stack trace / Error message

```code

```

## Your Environment

```code

```
