### ISSUE TITLE
ReDoc ImageField not displayed

### ISSUE THREAD

**Issue by BojanKogoj** [axnsan12/drf-yasg#95]
I have the following serializer, which will show `avatar` field in Swagger, but not ReDoc

```python
class AvatarUpdateSerializer(serializers.ModelSerializer):
    avatar = serializers.ImageField()

    class Meta:
        model = User
        fields = ('avatar',)
```

Screenshots
- Swagger
![screen shot 2018-04-03 at 15 09 24](https://user-images.githubusercontent.com/634075/38251538-001d439a-3752-11e8-95ef-8de06f9bb423.png)
- Redoc
![screen shot 2018-04-03 at 15 17 10](https://user-images.githubusercontent.com/634075/38251576-1e0cb840-3752-11e8-93b4-5a2746b6202e.png)

Is this an issue with this library or ReDoc?

**Comment by axnsan12** [comment]
Without the generated swagger YAML or JSON, I couldn't tell. However given that ``swagger-ui`` works I would suppose it's a bug in ReDoc.

**Comment by BojanKogoj** [comment]
In definitions I could find 
```yaml
  AvatarUpdate:
    type: object
    properties:
      avatar:
        title: Avatar
        type: string
        readOnly: true
        format: uri
```
That means it's ReDoc issue I suppose.
